### ISSUE TITLE
lesson's backend

### ISSUE THREAD

**Issue by enkhsaikhan1** [pinecone-studio/pinecone-intern-monorepo#1581]
```[tasklist]
### Tasks
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1588
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1594
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1592
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1593
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1603
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1611
```
