### ISSUE TITLE
Reorganize VS Code Structure to Include Admin Folder

### ISSUE THREAD

**Issue by enkhsaikhan1** [pinecone-studio/pinecone-intern-monorepo#1695]
```[tasklist]
### Tasks
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1720
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1766
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1765
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1692
```
