### ISSUE TITLE
Challenge's backend

### ISSUE THREAD

**Issue by enkhsaikhan1** [pinecone-studio/pinecone-intern-monorepo#1730]
```[tasklist]
### Tasks
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1756
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1731
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1739
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1746
```
