### ISSUE TITLE
Quiz's backend

### ISSUE THREAD

**Issue by enkhsaikhan1** [pinecone-studio/pinecone-intern-monorepo#1731]
```[tasklist]
### Tasks
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1733
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1734
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1735
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1736
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1737
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1738
```
