### ISSUE TITLE
Question's backend

### ISSUE THREAD

**Issue by enkhsaikhan1** [pinecone-studio/pinecone-intern-monorepo#1739]
```[tasklist]
### Tasks
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1740
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1741
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1742
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1743
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1744
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1745
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1808
```
