### ISSUE TITLE
Option's Backend

### ISSUE THREAD

**Issue by enkhsaikhan1** [pinecone-studio/pinecone-intern-monorepo#1746]
```[tasklist]
### Tasks
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1748
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1749
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1750
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1751
- [ ] https://github.com/pinecone-studio/pinecone-intern-monorepo/issues/1752
```
