### ISSUE TITLE
Admin quiz

### ISSUE THREAD

**Issue by enkhsaikhan1** [pinecone-studio/pinecone-intern-monorepo#1798]
```[tasklist]
### Tasks
- [x] Create quiz when create course
- [x] Quiz card
- [x] Quiz dynamic page
- [x] Create question dialog
- [x] Create a jest unit test for creating question dialog component
- [x] Create cypress e2e test for creating question feature
- [x] Question card
```
## Example UI
<img width="1440" alt="Screenshot 2024-07-23 at 12 59 34" src="https://github.com/user-attachments/assets/b9a736ec-af9f-4724-8fd4-909e99c75765">
<img width="1440" alt="Screenshot 2024-07-23 at 13 03 06" src="https://github.com/user-attachments/assets/3ed52d68-b493-4713-aafd-7bf34f4805ad">

## Example dynamic lesson and quiz page
<img width="1440" alt="Screenshot 2024-07-24 at 15 16 52" src="https://github.com/user-attachments/assets/ee48ea95-ae6c-49d5-8085-a0a769ea3458">
